PREFIX pdp: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX termit: <http://onto.fel.cvut.cz/ontologies/application/termit/pojem/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    skos:Concept termit:has-count ?count
} WHERE {
    SELECT (COUNT(DISTINCT ?asset) AS ?count) {
        GRAPH ?v {
            ?asset a skos:Concept .
            ?v <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/má-glosář> ?g .
            FILTER NOT EXISTS {
                ?asset a pdp:verze-pojmu .
            }
        }
    }
}
