const ConfigParam = {
    ADMIN_REGISTRATION_ONLY: "ADMIN_REGISTRATION_ONLY",
    SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED: "SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED",
    MOCK_REST_API: "MOCK_REST_API"
}

export default ConfigParam;