const ConfigParam = {
  ADMIN_REGISTRATION_ONLY: "ADMIN_REGISTRATION_ONLY",
  SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED: "SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED",
  MOCK_REST_API: "MOCK_REST_API",
  AUTH_TYPE: "AUTHENTICATION",
  AUTH_SERVER_MANAGEMENT_URL: "AUTH_SERVER_MANAGEMENT",
  AUTH_SERVER_USER_PROFILE_URL: "AUTH_SERVER_USER_PROFILE",
};

export default ConfigParam;
