const ConfigParam = {
  ADMIN_REGISTRATION_ONLY: "ADMIN_REGISTRATION_ONLY",
  SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED: "SHOW_PUBLIC_VIEW_ON_UNAUTHORIZED",
  AUTH_TYPE: "AUTHENTICATION",
  AUTH_SERVER_MANAGEMENT_URL: "AUTH_SERVER_MANAGEMENT",
  AUTH_SERVER_USER_PROFILE_URL: "AUTH_SERVER_USER_PROFILE",
  DISABLE_PUBLIC_VIEW: "DISABLE_PUBLIC_VIEW",
};

export default ConfigParam;
