enum ResourceSaveReason {
  NEW_OCCURRENCE = "NEW_OCCURRENCE",
  REMOVE_OCCURRENCE = "REMOVE_OCCURRENCE",
  OCCURRENCE_STATE_CHANGE = "OCCURRENCE_STATE_CHANGE",
  CREATE_FILE = "CREATE_FILE",
  REUPLOAD = "REUPLOAD",
  UNKNOWN = "UNKNOWN",
}

export default ResourceSaveReason;
